### ISSUE TITLE
escape "<" char from command line

### ISSUE THREAD

**Issue by xp-1000** [knqyf263/pet#102]
Hello,

Thanks for your work, I installed and tested pet from today only and it seems very promising.

I did not find the way to escape "special" char when adding new command.

Imagine this snippet :
```[[snippets]]
  description = "List RDS snapshots older than <date> from <profile> for <region>"
  command = "aws --profile <profile> rds describe-db-snapshots --region <region> --query 'DBSnapshots[?SnapshotCreateTime<=`<date>`]'"
```

The problem is that `<=` starts a new parameter whereas it is part of the command (not a variable like "date").

May be someone know how to escape first `<` ?

thanks

**Comment by artloder** [comment]
I use pet to generate parameterized sql queries and had to work around this by replacing all occurrences of `<=` with `<` but would love to avoid that.

**Comment by brandonkal** [comment]
I would prefer lower cased shell environment variables. Then you can use normal escaping rules.

**Comment by varenc** [comment]
I just started using the `superpet` fork and pet and it seems to fix this issue.  Or at least, it doesn't interpret '<=' as a parameter. https://github.com/RamiAwar/superpet

(no offense to pet, I love it! And superpet is just pet with a few extra fixes)

**Comment by RamiAwar** [comment]
Hey! Developer of superpet here, I fixed this issue in Pet now. I'm maintaining pet nearly every day nowadays so expect a lot more improvements!

@varenc @xp-1000 

<img width="693" alt="image" src="https://github.com/knqyf263/pet/assets/8523191/9a7b596b-fedb-43af-a420-e5237008df37">
