### ISSUE TITLE
FR - allow to download gist snippet file

### ISSUE THREAD

**Issue by pbek** [knqyf263/pet#105]
Thank you for pet, I love it and am using it for syncing my ssh connection commands.

I think I had the same issue like #99.

- added some snippets on one computer (KDE Neon, Ubuntu based, pet installed via deb file)
- synced them to a gist
- installed pet on a 2nd computer (Manjaro via yaourt)
- created new GitHub access token and added gist id of first computer
- typed `pet sync` on 2nd computer
- ~~empty `pet-snippet.toml` was uploaded~~ `pet-snippet.toml` was removed in the gist ~~and overwrote snippets from 1st computer~~

It would be really great to have a `pet upload` and `pet download` command to force upload or download.

**Comment by NickLarsenNZ** [comment]
It seems to be when you first install/configure on the additional machines. When I got home to my original one, I ran two consecutive syncs:

```
$ pet sync
Download success  
$ pet sync
Upload success     
```

Until there's a fix, for anyone needing to restore their gist, you can clone it, rebase, and push back up:

```sh
git clone https://gist.github.com/$USER/$GIST_ID
git log # find which commit you want to roll back to, copy the commit ID
git rebase e0a39d58^
git push --force-with-lease
```

**Comment by pbek** [comment]
Thank you 😉

**Comment by pbek** [comment]
I guess https://github.com/knqyf263/pet/pull/110 would fix the issue.

**Comment by knqyf263** [comment]
@pbek @NickLarsenNZ I'm sorry for my late reply. Thank you for investigating the issue. I will check #110.

**Comment by pbek** [comment]
Great :smile:

**Comment by knqyf263** [comment]
@pbek I've merged your PR. Thanks😄

**Comment by pbek** [comment]
Awesome!
