### ISSUE TITLE
More than one line in description field?

### ISSUE THREAD

**Issue by ubersol** [knqyf263/pet#11]
I love the tool, i really think it is awesome. A quick enhancement request:

Is it possible to extend the description field to include new lines? so that I can include examples of what actually command is doing by supplying an output of a command that contains more than one line?

For example here is a command:
awk -F'|' '{print $2,$3,$5,$6}' myfile.txt | awk '{$1=$1};1'  |   awk NF

and the output
order1 requested shipped 12/12/12
order2 requested halted    12/12/12
....

how can I include an output like above in the description field?

**Comment by knqyf263** [comment]
Currently, only one line can be registered in description.
If you want to register output, how about adding a column for output?
It's simple, so I can implement it right away.
However, you can display `output` field only in `pet list`.

**Comment by ubersol** [comment]
Yes, that would probably work too...Thank you for that! This would be an optional column then right ?
As a workaround I tried to edit snippet.taml by using  pet edit like this:

`[[snippets]]
  description = "Print a Nice Directory Structure"
  command = "find . -type d -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
  output = "blah blah"`

but that did not work and obviously this is one line input too. :(

Anyways, I'll wait to see your solution!

Thanks again!

**Comment by knqyf263** [comment]
@ubersol I added output column. How about this?
If there is any problem, please tell me!
