### ISSUE TITLE
[question] any idea why virustotal shows `invoice.exe` as process created?

### ISSUE THREAD

**Issue by c33s** [knqyf263/pet#111]
```
Processes created

    invoice.exe
```

https://www.virustotal.com/gui/file/755848ec291b2ae53bd5c29155d5363b976ffdae6a5870aa0be323eee883dea2/behavior/VirusTotal%20Jujubox

https://vtbehaviour.commondatastorage.googleapis.com/755848ec291b2ae53bd5c29155d5363b976ffdae6a5870aa0be323eee883dea2_VirusTotal%20Jujubox.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1565531908&Signature=sy3n7BwTE4npFtLQ0MfU8NMDlH5NRLJciTRGR%2Bkp9DZgSqqTtSvilaCHZ0nIDvPem%2F0joF%2Fc8k78%0A3mbXxvoSZOFvRrepu3Nyvu7QnU5mmt3%2BWtn9Kwk4t%2BMjeK9HuC5YLRczbNer8rMYTy4x5fBuOBcs%0AeulR6TIVKy1beOexVTk%3D&response-content-type=text%2Fhtml;

**Comment by knqyf263** [comment]
I don't use Windows, so I have no idea...
