### ISSUE TITLE
[Feature] arguments for parameter

### ISSUE THREAD

**Issue by fentas** [knqyf263/pet#117]
E.g. I have the following command
```
ffmpeg -i <input> -vf "fps=<fps=10>,scale=<scale-width=1080>:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop <loop=0> <output>.gif
```

I would like to have the ability to pass arguments to `pet` like
```
pet exec ./video.mkv ./converted-video
```

can imagine passing this like e.g. `<input=$arg1>`

**Comment by RamiAwar** [comment]
Interesting suggestion @fentas , although you'd still have to go in and select the command. Feels weird that you have to memorize the input args to your command though.

I like the idea of speeding things up but the user experience of this doesn't seem optimal yet. Will add this suggestion to another ticket on using pet with more speed and ease though.
