### ISSUE TITLE
Pet Sync behind corporate proxy

### ISSUE THREAD

**Issue by jamespoore** [knqyf263/pet#118]
Hi there,

Firstly thank you for creating this tool. It's great and I use it every day!

I've started syncing my collection of Snippets to Gist and this works absolutely fine when not on the corporate network (surprise surprise!). When using the work network I get this error:

`pet sync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75b4a8]

goroutine 1 [running]:
github.com/knqyf263/pet/sync.getGist(0xc4200134a0, 0x20, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/pet/sync/sync.go:60 +0x178
github.com/knqyf263/pet/sync.AutoSync(0xc4200133b0, 0x24, 0x5a1000, 0xc420055cc8)
	/home/travis/gopath/src/github.com/knqyf263/pet/sync/sync.go:26 +0x54
github.com/knqyf263/pet/cmd.sync(0xb13780, 0xb33470, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/knqyf263/pet/cmd/sync.go:27 +0x9b
github.com/knqyf263/pet/vendor/github.com/spf13/cobra.(*Command).execute(0xb13780, 0xb33470, 0x0, 0x0, 0xb13780, 0xb33470)
	/home/travis/gopath/src/github.com/knqyf263/pet/vendor/github.com/spf13/cobra/command.go:698 +0x47b
github.com/knqyf263/pet/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xb13120, 0xc420078058, 0x0, 0x8bbac0)
	/home/travis/gopath/src/github.com/knqyf263/pet/vendor/github.com/spf13/cobra/command.go:783 +0x349
github.com/knqyf263/pet/vendor/github.com/spf13/cobra.(*Command).Execute(0xb13120, 0xb13120, 0xc420055f50)
	/home/travis/gopath/src/github.com/knqyf263/pet/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/knqyf263/pet/cmd.Execute()
	/home/travis/gopath/src/github.com/knqyf263/pet/cmd/root.go:49 +0x31
main.main()
	/home/travis/gopath/src/github.com/knqyf263/pet/main.go:20 +0x20`

I presume this is something to do with the proxy running here, it normally is. It is a MITM proxy.

My issue is how do I provide Pet (/go) the proxy settings so the sync works. I read some hits on google which suggested making sure the system proxy is set (it is in bashrc) and also in git config, this is also already set. So I am a bit stuck now.

Appreciate any input & keep up the good work.

James

**Comment by hoshsadiq** [comment]
Does the corporate proxy block gist? If so, I don't think this is possible. If they don't block gist then, you should be able to export the following variables:
```
PROXY_USER="myuser"
PROXY_PASS="mypass"
PROXY_HOST="proxy.mycorp.com"
PROXY_PORT="8080"

export http_proxy="http://${PROXY_USER}:${PROXY_PASS}@${PROXY_HOST}:${PROXY_PORT}"
export https_proxy="$http_proxy"
export HTTP_PROXY="$http_proxy"
export HTTPS_PROXY="$https_proxy"
```

Simply find the above details and fill them out, and put them in your `.bashrc` or `.zshrc` or `.profile` or something. You should note that some corporations will separate `http` and `https` proxy traffic, but it might not be needed.

Lastly, if other things break (specifically internal domains that should not be routed through the proxy), you should also export the variables `no_proxy` and `NO_PROXY`, which should be a comma separate list of hosts that should not be routed through the proxy, e.g.:
```
no_proxy="localhost,127.0.0.1,corp.com"
NO_PROXY="$no_proxy"
```

**Comment by jamespoore** [comment]
Thank you, this now works as expected!
