### ISSUE TITLE
Equal sign in parameter

### ISSUE THREAD

**Issue by Spacewalker2** [knqyf263/pet#119]
Hello,

first of all thanks for this nice tools. Is it possible to use a equal sign in an parameter in my snippet file like <filter=trace=all>? If I use this and run this snippet pet cuts the default value after trace. I tried escaping and quoting but it didn't work.

**Comment by alem0lars** [comment]
I'm still facing the same problem

**Comment by RamiAwar** [comment]
Yeah this isn't supported yet, I'll look into it in a sec see if it's an easy addition.

**Comment by RamiAwar** [comment]
That was indeed an easy fix! Thanks for reporting this @alem0lars @Spacewalker2, and sorry for the super long delay in responding!
