### ISSUE TITLE
Replace sh with bash

### ISSUE THREAD

**Issue by jza34** [knqyf263/pet#123]
Hi, I get some sh errors with some of my snippets...How to configure pet to execute theses snippets with bash?
Example : a snippet with the source command (only known by bash)
Thanks!

**Comment by brandonkal** [comment]
Pet should read SHELL and execute with that. Though bash is slower to start. Maybe allow users to put a `PET_SHELL=$SHELL` in their profiles.

**Comment by dkrm0** [comment]
The `source` built-in command is just an alias to the `.` built-in command. The [dot](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_18) built-in command is a POSIX requirement for any `sh` implementation, so it'll be more ubiquitous than `source`.

**Comment by RamiAwar** [comment]
Hey @jza34 , `source` works fine for me using sh though.

I like this suggestion however @brandonkal , will add this as an improvement. Should be easy to implement as well!
