### ISSUE TITLE
Ordering of Multiple Parameters is Random

### ISSUE THREAD

**Issue by natehouk** [knqyf263/pet#130]
When searching or executing a command that has multiple parameters, the order of the parameters is shown in a random order.

Sometimes it will show the parameters in the order of which they appear in the command. Other times, they will appear in a different order. The ordering appears to be random.

This makes using the tool very difficult. This was tested with a command with 5 parameters.

**Comment by jaroslawhartman** [comment]
Will be implemented as Enh #258

**Comment by RamiAwar** [comment]
@natehouk This is released now, thanks!
