### ISSUE TITLE
Print Command Snippet For other Uses

### ISSUE THREAD

**Issue by Rahulsharma0810** [knqyf263/pet#137]
Feature Request

This is a wonderful tool, But it works only in local system terminal. It would be great to print or copy a snippet in the clipboard to use with other programs.

We all use SSH and save our snippet locally, But when it comes to run that on the server, I have to go to `pet edit` and manually copy that command.

![image](https://user-images.githubusercontent.com/9934859/83277468-b7bb9100-a1ef-11ea-9e02-968f25431ccb.png)

A sample tool for this functionality is https://www.renfei.org/snippets-lab/

Regards,
Rahul Sharma

**Comment by czeigler** [comment]
I would really like something like this as well.  It seems like there could be another subcommand, something like "pet print" where it lets you search your snippets and if you make a selection it just echos the output to the shell where you can then copy it or modify it and run it.

**Comment by iAugur** [comment]
pet search does that - it prints the selected command without executing it

**Comment by crile** [comment]
Sure, `pet search` do it, as resquested.
However, my workflow is :
* type `pet search`
* copy with the mouse the result
* paste the command

It will be great if `pet search` can have an option to copy directly in the clipboard. Or another command likes `pet clip`

I try to do some workaround with command line tool that allow to write in the clipboard but it overloads my pet snippets.
Or it is not convenient

**Comment by RamiAwar** [comment]
Supported!
