### ISSUE TITLE
Bug: <...> expression in description are considered as parameter.

### ISSUE THREAD

**Issue by firmart** [knqyf263/pet#150]
I accidentally found that  <...> expression in description are considered as parameter.
Example below (paste it after `pet edit`):

```
[[snippets]]
  description = "Very basic command with <param_1=default>, ..., <param_n=default>"
  command = "echo \"This function has no parameter.\""
  output = ""
```

Screenshot:

![Screenshot from 2020-12-06 02-40-22](https://user-images.githubusercontent.com/20540328/101269199-7989c600-376c-11eb-8cf2-9a8ce7fb9e77.png)

pet version: 0.3.6

**Comment by RamiAwar** [comment]
What a find! Nice one! Will add it as a high prio bug, super weird one
