### ISSUE TITLE
Katacoda tutorial to demonstrate Pet - request review and suggest add to readme.

### ISSUE THREAD

**Issue by javajon** [knqyf263/pet#151]
Hi Pet team (@knqyf263). I'm happy to offer a public/free Katacoda scenario that demonstrates the advantages and features of Pet. The scenario is here: [Pet, a CLI Snippet Manager](https://katacoda.com/javajon/courses/kubernetes-tools/snippets-pet). Can I ask the Pet project decision leader(s):

1. Provide feedback on the scenario.
2. Let me know if I should add a PR to the readme to link to this scenario?

Great project!

**Comment by knqyf263** [comment]
Awesome!!

>Let me know if I should add a PR to the readme to link to this scenario?

Yes, it would be great if you send the PR.

![image](https://user-images.githubusercontent.com/2253692/103503945-980fd980-4e5e-11eb-80db-b1169f8fd8ac.png)

The title looks like "Nginx on Kubernetes".

**Comment by javajon** [comment]
Thank you for the review. I polished up the introduction page and added the PR for the README. Let me know if you find any other needed edits in the scenario.
