### ISSUE TITLE
Build with Raspberry Pi4 Manjaro/Archlinux

### ISSUE THREAD

**Issue by jza34** [knqyf263/pet#157]
Hi,
I start to replace my desktop with a raspberry pi and it goes well. But unfortunately Pet is not released under arm architecture yet.
So I have followed your instruction to build it but I get an error : 

```
[moi@pi pet]$ make install
go get -u github.com/golang/dep/...
# github.com/golang/dep/gps
../../../../pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:103:21: cannot use sv (type *semver.Version) as type semver.Version in field value
../../../../pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:122:16: invalid type assertion: c.(semver.Version) (non-interface type *semver.Constraints on left)
../../../../pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
make: *** [Makefile:23 : dep] Erreur 2
```

Any advice ? Do you plan to release an ARM version ?

Thanks all!

**Comment by RamiAwar** [comment]
Hey @jza34 ! This might be supported now thanks to new arm mac builds. Sorry for the super delayed response.
