### ISSUE TITLE
Configure Text Wrapping in Completion Boxes

### ISSUE THREAD

**Issue by jkroes** [knqyf263/pet#166]
In the README, an example of variable completion is shown: 

<img width="657" alt="Screen Shot 2021-04-14 at 9 31 32 PM" src="https://user-images.githubusercontent.com/18478163/114814567-4a621180-9d69-11eb-85a2-3776c37292bd.png">

In contrast, I haven't been able to replicate text wrapping in zsh on arm64 MacOS (homebrew installation). 

<img width="599" alt="Screen Shot 2021-04-14 at 9 39 14 PM" src="https://user-images.githubusercontent.com/18478163/114814828-decc7400-9d69-11eb-97b7-0d6489a66a90.png">

**Comment by jkroes** [comment]
I enabled scrolling horizontally during queries by configuring `selectcmd = "peco"` and configuring peco; however, that still leaves the issue above with not being able to see the third parameter/variable in the second image, due to a lack of text wrapping or scrolling.

**Comment by RamiAwar** [comment]
Thanks for reporting this, does indeed look like a bug to me, happening locally as well.

**Comment by RamiAwar** [comment]
So I'm not sure why this was set to Wrap = false, but I'm just going to change it to true. Seems to fix it on my mac.

<img width="269" alt="image" src="https://github.com/knqyf263/pet/assets/8523191/c17fa0b9-7d23-41b9-a90f-3bb531dbed34">

<img width="418" alt="image" src="https://github.com/knqyf263/pet/assets/8523191/49d47b87-f96b-43aa-bc74-0997175987ed">
