### ISSUE TITLE
Unable to set Gist ID and the access token from the Environment Variable

### ISSUE THREAD

**Issue by hariprasadraja** [knqyf263/pet#167]
For security reasons, I don't want to disclose my gist access token and gist id in the config file and saved it as an environment variable. 

`General`  settings can read the environment variables  but  `Gist`  is unable to do the same.  

```
❯ pet sync
Failed to get gist: GET https://api.github.com/gists/$%7BGIST_TOKEN%7D: 401 Bad credentials []
❯ export GIST_TOKEN='abcd'
❯ pet sync
Failed to get gist: GET https://api.github.com/gists/$%7BGIST_TOKEN%7D: 401 Bad credentials []
❯ echo $GIST_TOKEN
abcd
```

```
[General]
backend = "gist"
column = 60
editor = "micro -config-dir ${DOTFILES_PATH}/configs/micro"
selectcmd = "fzf"
snippetfile = "${DOTFILES_PATH}/configs/pet/snippet.toml"
sortby = "description"

[Gist]
access_token = "${GIST_TOKEN}"
auto_sync = true
file_name = "pet-snippet.toml"
gist_id = "${GIST_ID}"
public = false

```

**Comment by janneliukkonen** [comment]
Leave the GIST_ID and GIST_TOKEN empty at the configuration file. Use `PET_GITHUB_ACCESS_TOKEN` env variable as stated in the README https://github.com/knqyf263/pet#gist.

Set the gist id in the configuration to the one you receive from first `sync` run.
