### ISSUE TITLE
Reliance on deprecated `dep` tool means `pet` does not compile on OpenBSD

### ISSUE THREAD

**Issue by elmarsto** [knqyf263/pet#176]
Expected behaviour:

 - Pet compiles

Actual behaviour: 

 - Pet errors out; dep is (ironically) dep-recated, and there is apparently no history of working builds for OpenBSD.

![image](https://user-images.githubusercontent.com/315987/131233606-8ecfb670-011e-4d99-8081-b775e94554a5.png)

**Comment by qbit** [comment]
`dep` can be installed on OpenBSD via `pkg_add` - OpenBSD 6.9 has dep at version `0.5.0` which should work. You will need to remove the `dep` dependency from the build target in the Makefile.

Alternatively, `portgen go github.com/knqyf263/pet` can be used to build a package that can be installed with `pkg_add`.

I was able to build it successfully:

```
qbit@tal[0]:/usr/ports/mystuff/go/pet got:(master)$ make package
`/build/pobj/pet-0.3.6/fake-amd64/.fake_done' is up to date.
===>  Building package for pet-0.3.6
Create /usr/ports/packages/amd64/all/pet-0.3.6.tgz
Creating package pet-0.3.6
qbit@tal[0]:/usr/ports/mystuff/go/pet got:(master)$ 
```

(you will need the ports tree in place to run portgen which lives in /usr/ports/infrastructure/bin/portgen)

Anyway - I can't speak to the pet's use of dep - I am just offering this info in the hopes it helps you get up and running sooner :D

**Comment by RamiAwar** [comment]
Should be resolved now!
