### ISSUE TITLE
[Bug] Pasting long text in the argument windows does not work correctly - adds spaces between characters for long strings

### ISSUE THREAD

**Issue by mojothejojo** [knqyf263/pet#179]
1. in the argument window - when small text is pasted works fine - but when larger text is pasted - it introduces spaces between the characters  - eg consider:
     * when pasting `google.com` it will be pasted as => `google.com`
     * but on pasting `tiralgooglecomwebsitetobetigt.com` => `tiralgooglecomwebsi t e to b e t i g t . c o m`
2. Consider this screenshot
<img width="1037" alt="Screenshot 2021-09-20 at 6 04 13 PM" src="https://user-images.githubusercontent.com/16579106/134003585-84978024-a163-4389-b693-9a31733842b3.png">

**Platform** : Mac - BigSur
**Key being pressed** : Command+V

**Comment by bergercookie** [comment]
Is there any update on this?
It's one of the issues that if solved would considerably improve the UI experience of this tool


@knqyf263 any insight as to the area that this bug  may reside?

**Comment by finzzz** [comment]
related to #132
root cause: https://github.com/jroimartin/gocui/issues/187
