### ISSUE TITLE
[Feature Request] Profile

### ISSUE THREAD

**Issue by finzzz** [knqyf263/pet#189]
Hello,

Thanks for the app.

I have over hundreds of snippets, so I need to separate some of my snippets according to their category. For example `pet search --profile=kubernetes` or `pet search --profile=all` when I want to search among all profiles.

**Comment by crc-smcleod** [comment]
Have you tried using tags?

**Comment by RamiAwar** [comment]
I think tags solves this problem exactly! Check them out
