### ISSUE TITLE
How to enable color when using the function pet-select ZSH function?

### ISSUE THREAD

**Issue by progS1m** [knqyf263/pet#195]
I've tried to add --color option to the pet-select ZSH function but it does change nothing and the color do not appear.
Tried two variants (.zshr) :
```
...
function pet-select() {
--
130 | BUFFER=$(pet search --color --query "$LBUFFER")
...
```

or

```
...
function pet-select() {
--
130 | BUFFER=$(pet search --query "$LBUFFER" --color)
...
```

Using the pet search --color brings the colorized version.

**Comment by lrworth** [comment]
I see the same thing in bash. Running `pet search --color` displays coloured output, but `$(pet search --color)` does not.
