### ISSUE TITLE
[Bug] Two character variables cause a problem with input boxes

### ISSUE THREAD

**Issue by smnshw** [knqyf263/pet#206]
When only two characters are used for a variable it prevents the next variable's input box from displaying. 

For example...

`rdesktop <ip address> -u <username>` works and displays both input boxes whereas `rdesktop <ip> -u <username>` only displays the first input box.

**Comment by varenc** [comment]
I switched to using the `superpet` fork of pet and it resolves this issue: https://github.com/PwnedShell/superpet/

(I do really love pet! And superpet is just pet with a few extra bug fixes)

**Comment by RamiAwar** [comment]
@varenc Thanks for sharing this fork of Superpet! I never thought anyone forked it, will check those out and see what they did as well. I just became a collaborator on Pet and we'll implement all of those and more here now!

**Comment by RamiAwar** [comment]
This is going to be the first fix we merge here, will let you know when it's merged and released
