### ISSUE TITLE
Dialog inputs bug and an improvement

### ISSUE THREAD

**Issue by matiwinnetou** [knqyf263/pet#21]
Dialog inputs for parameter variables is absolutely awesome, however I detected one bug and one possible improvement:

Bug:
- when text is long often extra whitespaces are entered between lines

Improvement:
- input param dialogs could be as long as search command (top window)

**Comment by lulunevermind** [comment]
#24

**Comment by knqyf263** [comment]
@matiwinnetou Hi! Thank you for your report!
How are whitespaces are entered?
I entered the long characters, but whitespaces are not entered

![pet09](https://cloud.githubusercontent.com/assets/2253692/24330622/91a4146c-125d-11e7-9e70-728058901e4d.gif)

**Comment by matiwinnetou** [comment]
I was pasting the value from somewhere, whitespaces where entered on a long url entered in cone field. Perhaps it has something to do with url escaping not the length itself. I am not sure.

**Comment by knqyf263** [comment]
I think that there is no problem with the length of the view.
If you need a long view, how about the option (like `--long`)?

**Comment by leebradley** [comment]
Came across the same issue after using copy+paste. It appears to do with the implementation of the view.

![pet paste bug](https://cloud.githubusercontent.com/assets/597352/25257781/4bfa2898-25ef-11e7-9383-da60d9713697.gif)
