### ISSUE TITLE
Add categories to group commands

### ISSUE THREAD

**Issue by Adelante10k** [knqyf263/pet#215]
**Will be nice to have**:

- `pet category <category name>`
- `pet list category` - list all categories
- `pet new -t -c `- Add command to tag and category
- `pet search category` > Select category - `list` all commands from specific category
- `pet exec -c `> Select category - List to `exec` commands from specific category

If category exist, to add command to that category, if not, to create that category, related to `pet new -t -c`.

Think for example of `curl`, `awk` or `nmap` commands, where categorization would simplify visibility mapping, productivity and speed.

Thanks!

**Comment by RamiAwar** [comment]
This is what tags are for! Check out the docs on tags 😃
