### ISSUE TITLE
New maintainers needed

### ISSUE THREAD

**Issue by guettli** [knqyf263/pet#218]
The last commit is many months old.

It looks like this projects is no longer maintained.

Which alternative are feasible?

**Comment by knqyf263** [comment]
I've cut v0.5.0 right now.
I don't actively maintain it because I'm busy with my personal life now, but I want to work on it when I have time.
That being said, I obviously need someone's help.

@riscie Are you interested in maintaining the project?

**Comment by riscie** [comment]
I am quite honored that you reach out. I really like pet and still use it daily. 

However I would need to brush up my go skills quite a bit as I am doing mainly C# and typescript these days. Also I have a lot going on privately with my family atm so I dont think I would be the best fit. 
do you have any alternatives?

By the way, great to hear you were able to do another release.

**Comment by knqyf263** [comment]
>Also I have a lot going on privately with my family atm

Me too. I got kids, and it changed my whole life...

>do you have any alternatives?

I will call for maintainers.

**Comment by riscie** [comment]
We are in the same boat with the kids thing 😅

**Comment by guettli** [comment]
Me, too. Family is important. But maybe there are young and motivated people out there? Don't be afraid, I guess the current maintainers will help you to do your first steps.

**Comment by lasantosr** [comment]
I've just created a Rust project that might fit as a replacement for this one, in case you can't find maintainers (i've never used go)
https://github.com/lasantosr/intelli-shell

It's pretty young but useful

**Comment by sbstn87** [comment]
There's also hoard:
https://github.com/Hyde46/hoard

**Comment by RamiAwar** [comment]
I extended it a bit in https://github.com/RamiAwar/superpet, tried adding some ideas here but at the time no one responded so I just continued working on the fork. I might be able to help, I still use this tool daily!

**Comment by knqyf263** [comment]
I'm sorry I have been unavailable for a while. If you don't mind, I'll invite you as a maintainer.

**Comment by RamiAwar** [comment]
@knqyf263 Yeah feel free to share what you used to do in terms of responsibilities, and I'll try my best to help!

**Comment by knqyf263** [comment]
Thanks! I've invited you.

**Comment by knqyf263** [comment]
Closing it as @RamiAwar joined.
