### ISSUE TITLE
Enhancement for README: Configuration settings to improve pet search layout

### ISSUE THREAD

**Issue by kalip2** [knqyf263/pet#265]
I'd recommend updating the README to include this option in `config.toml`:

```
selectcmd = "fzf --ansi --layout=reverse --border --height=90% --pointer='*' --cycle --prompt='Snippets: '"
```

Adding that would bring the search familiarity of other applications like `git log` and `history` to  `pet search --color`

### Before
<img width="718" alt="Screenshot 2024-02-04 at 2 45 43 PM" src="https://github.com/knqyf263/pet/assets/135771736/f8b0801e-7266-4e8b-9ebb-ebde08cf3987">

### After
<img width="725" alt="Screenshot 2024-02-04 at 2 44 29 PM" src="https://github.com/knqyf263/pet/assets/135771736/be49be11-9a22-4a0d-bc9c-ea7ba9b2edb9">

**Comment by RamiAwar** [comment]
Thanks @kalip2 , great suggestion. Are you interested in submitting a PR yourself? 😃
