### ISSUE TITLE
command to edit does not work on Windows unless configuring a Unix-like editor

### ISSUE THREAD

**Issue by cderv** [knqyf263/pet#314]
### Privileged issue

- [X] I've been directed through ~Discussions~ another issue to create an issue here.

### Issue Content

Related to 
- #140 

but it does not work on Powershell nor CMD/

````
❯ pet configure
'+0' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
exit status 1
````

(error in french, but basically command run is not windows compatible)

This is because the function to edit file is not Windows compatible
https://github.com/knqyf263/pet/blob/f88549cbb1e7eb4853bf7929b659e083076bfc92/cmd/util.go#L17-L22

Configuring the editor can help if using one supportin `+<line>` work - like a Unix-like one

````toml
[General]
  Editor = "vim"
````

(`vim` or equivalent can be made installed with Scoop)

Then I can make it work with CMD (default). 

It could be good to be able to support for Windows notepad or any other program like VSCOE (`Editor = "code"`).

**Comment by RamiAwar** [comment]
Hmm interesting, wonder why we don't clean up the args when using the generic command from conf.

Will look into this one. Tricky to change tho as it might break for people depending on it

**Comment by jaroslawhartman** [comment]
I can confirm similar behaviour on MacOS - I have VSCode configured for edit and it's opening `+0` file as well:
![image](https://github.com/user-attachments/assets/eea896ba-1ba2-4a28-b644-fc6da439e55a)

**Comment by RamiAwar** [comment]
Indeed @jaroslawhartman , the +0 is added for editors like vi, vim, nano, etc. to jump to the end of the file where the new snippet is inserted and put the cursor in a place where the user can just start typing.

I think the most straightforward solution to this would be to add some conditionals there, depending on the editor that's being used.
