### ISSUE TITLE
Suggestion: tags?

### ISSUE THREAD

**Issue by streeck** [knqyf263/pet#36]
It would be nice to have the option of tagging snippets. For instance:
```bash
$ pet new 'rabbitmqctl status' --tags rabbitmq
$ pet new 'celery worker -A celery_worker.celery --loglevel=info' --tags celery python flask
```

And later when searching or listing it would be nice to be able to filter by certain tags.

What do you think?

**Comment by matiwinnetou** [comment]
I think it is a good idea, I simulate this today by always appending tag at the beginning of command, e.g.

git branch -lvv

**Comment by knqyf263** [comment]
@streeck Thanks for your advice! Nice idea.
How do you want to search snippets with tags?

Incremental search?
```
$ pet search
[Description] celery worker -A celery_worker.celery --loglevel=info (celery python flask)
```

or specify tags by `--tags` option?
```
$ pet search --tags python # Display only snippets tagged with python
[Description] celery worker -A celery_worker.celery --loglevel=info
```

**Comment by streeck** [comment]
@knqyf263, maybe during search I could indicate a tag with `#`, for example:

```bash
$ pet search
#python #flask from here on normal search
```
Specifying the tags at the beginning should be easy to implement and guarantees that the "filtering" comes first, and then you can start searching the results. What do you think?

I liked the incremental search idea by the way.

Specifying `--tags` would lock that `pet search` only to the tags specified at the moment of the call, if I change my mind I'd have to quit and call `pet search` again, right?

**Comment by knqyf263** [comment]
@streeck I got it.
I tried implementing this feature.
See https://github.com/knqyf263/pet#tag.

Please tell me if you have any feedback!

**Comment by streeck** [comment]
@knqyf263 nice one! Keep up the great work!
