### ISSUE TITLE
Full description text is not showing in command line

### ISSUE THREAD

**Issue by jitendravyas** [knqyf263/pet#46]
<img width="753" alt="monosnap 2017-05-17 14-26-48" src="https://cloud.githubusercontent.com/assets/77309/26186964/653f8a94-3bb3-11e7-8e61-80b01d3ec653.png">

**Comment by taylankasap** [comment]
Horizontal scroll and/or toggle wrap functionality might be the way to go.
@RamiAwar any insights on this?

**Comment by RamiAwar** [comment]
I think it will depend on the "command selector" we're using.

By default, we use fzf (configured in the config as selectCmd). Fzf is the one showing these commands and does not support wrapping the lines unfortunately.

The way it works also is searching per-line (so adding newlines is problematic) but I'm only 90% sure of this.

**Comment by RamiAwar** [comment]
I think this will be non-trivial to implement, and also I'd say the majority of snippets are pretty clear on what they do from what's visible of the description + tags so I wouldn't give this high priority from a product sense.

Not saying this is a bad idea, just not easy to do and not worth the time it's gonna take to investigate imo, so gonna close this until enough people bring it up!
