### ISSUE TITLE
Truncated default parameter value

### ISSUE THREAD

**Issue by artloder** [knqyf263/pet#56]
I'm new to pet, so maybe I'm missing something, but the following snippet in pet 0.2.3 renders the default value as `worl` instead of `world`:
```
[[snippets]]
  description = "Say hi"
  command = "echo \"Hello, <place=world>\""
  output = ""
```

**Comment by yuriipolishchuk** [comment]
Have the same issue on osx with pet 0.2.3

**Comment by rlovato** [comment]
+1. It looks like maybe one or more newlines or control characters are being inserted in place of the last character. Do a `pet search --query` and select a snippet with default parameters. If you tab to the param edit box and hit the down arrow, it scrolls the string up out of view.

**Comment by hitzhangjie** [comment]
pkg-config --cflags --libs <pkgname=glib-2.0>，which truncate default value from 'glib-2.0' to 'glib-2.' ......

**Comment by knqyf263** [comment]
I'm sorry for the late reply!
I released v0.2.4. This problem will be resolved.
https://github.com/knqyf263/pet/releases/tag/v0.2.4

Please try.

**Comment by yuriipolishchuk** [comment]
@knqyf263 it works! thank you!

**Comment by artloder** [comment]
Just seeing this... thanks for the fix!
