### ISSUE TITLE
Variables via input dialog

### ISSUE THREAD

**Issue by matiwinnetou** [knqyf263/pet#6]
Thank you for this awesome project, I have an idea to extend the project with ability to pass variables. There could be some integration (dialog) that would ask a user with what variable values he/she wants to execute a command.

Let's take an example of removing a branch in git locally and remotely I often do:

git branch -D <branch_name> && git push --delete origin <branch_name>

such command could open a popup (dialog) where I could enter branch_name and then command would fill up the variables and execute the chained set of commands.

What do you think?

**Comment by matiwinnetou** [comment]
(http://www.linuxjournal.com/article/2807)

**Comment by matiwinnetou** [comment]
What are your thoughts on this?

**Comment by mababio** [comment]
I know this doesn't help towards the cause, but I just wanted to express my love for this tool and my hopes for this feature. Rock on!

**Comment by knqyf263** [comment]
Nice idea!
Actually, before release, I wondered whether to implement this feature.
However, I wanted to make `pet` simple, so I released it without this feature.

If many people need this feature, I will implement it!

**Comment by nghialv** [comment]
👍

**Comment by matiwinnetou** [comment]
Thank you, what an awesome project. Already changing my command line life

**Comment by sunfmin** [comment]
👍  Need this feature~~

**Comment by knqyf263** [comment]
@matiwinnetou @mababio @sunfmin @nghialv 

@lulunevermind implemented this feature!
https://github.com/knqyf263/pet/pull/19

Please try it out! (I added the movie in README)

**Comment by matiwinnetou** [comment]
Awesome, I am so greatful for this feature!

**Comment by mababio** [comment]
Wow I'm loving it. Thank you so much @knqyf263
