### ISSUE TITLE
Placeholders do not behave well

### ISSUE THREAD

**Issue by branquito** [knqyf263/pet#64]
![image](https://user-images.githubusercontent.com/1226132/35184237-3a4c738a-fdf3-11e7-90af-f64dfc0ba881.png)
As you can see from the screenshot provided, both param values are missing the last character...
This was not an issue before, as I recall.

**Comment by knqyf263** [comment]
Thank you for the report!

What's your `pet` version? 
I fixed this bug before.
https://github.com/knqyf263/pet/pull/53

Please try the latest version!

**Comment by branquito** [comment]
Its 's `pet version 0.2.3`, otherwise very good tool. thanks for making this, it can be a life saver.

**Comment by knqyf263** [comment]
Thank you!
I released v0.2.4.
https://github.com/knqyf263/pet/releases/tag/v0.2.4

Please use this version.

**Comment by knqyf263** [comment]
Please reopen if there is any other problem.
