### ISSUE TITLE
Can't build from source: missing commands dep and vet

### ISSUE THREAD

**Issue by marcelpaulo** [knqyf263/pet#65]
I've discovered pet from [this article](https://www.ostechnix.com/pet-simple-command-line-snippet-manager/), and I'm trying to build it from source. I cloned the git repository and ran `make`, but commands `dep` and `vet` are missing.

My environment is Xubuntu 17.10. I searched for `dep` and `vet` in the Ubuntu repositories and didn't find them. Where do I install them from ?

**Comment by knqyf263** [comment]
@marcelpaulo At first, you need `go`.
Then just `make install`, not `make` !

**Comment by marcelpaulo** [comment]
I have installed go, from Ubuntu package `golang`. If I run `make install` the result will be the same, since it will first try to build pet, and the rule for target `dep` calls program **dep**.

**Comment by knqyf263** [comment]
fmm... I don't know why.
So, please try the following commands.
```
$ go get -u github.com/golang/dep/...
$ dep ensure
$ go install
```

**Comment by marcelpaulo** [comment]
I had tried that, @knqyf263, but `dep ensure` fails because _dep_ isn't installed:

```
paulo@monk:~/src/pet$ dep ensure
No command 'dep' found, did you mean:
 Command 'dwp' from package 'binutils' (main)
 Command 'rep' from package 'rep' (universe)
 Command 'iep' from package 'emboss' (universe)
 Command 'delp' from package 'fp-utils-3.0.2' (universe)
 Command 'xep' from package 'pvm-examples' (universe)
 Command 'dex' from package 'dex' (universe)
 Command 'dp' from package 'speech-tools' (universe)
dep: command not found
```

_dep_ doesn't seem to be in any Ubuntu package. I have searched for it with `apt-file -x search '\bdep$'` and none of the hits were executable.

**Comment by knqyf263** [comment]
I understand.
`go get -u github.com/golang/dep/...` this command will install binary on `$GOPATH/bin`.
So, you need to add `$GOPATH/bin` to $PATH!

**Comment by knqyf263** [comment]
And you should clone on `$GOPATH/src`.

If it is difficult to build from source, binary installation is recommended.
https://github.com/knqyf263/pet/releases/tag/v0.2.4

**Comment by marcelpaulo** [comment]
Oh, I see ... Well then, _GOPATH_ is not set. I logged out and back in, but it's still not set. How do I discover the correct path to set it ?

**Comment by knqyf263** [comment]
You must set by yourself.
This is my setting.
```
$ vim .zshrc
export GOPATH=$HOME
export PATH=$PATH:$GOPATH/bin
```

**Comment by marcelpaulo** [comment]
My sincere apologies, I found the value for **GOPATH** by running `go env`:

```
paulo@monk:~$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/paulo/go"
GORACE=""
GOROOT="/usr/lib/go-1.8"
GOTOOLDIR="/usr/lib/go-1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build091644269=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Thanks for your patience, @knqyf263 ! As you can see, it's the very first time I use **go**, so I'm stumbling across some very basic errors. I'll go ahead and build **pet** now.

Once again, thanks for your swift assistance !

**Comment by knqyf263** [comment]
@marcelpaulo No problem!
Please feel free to ask me if you have any question.

**Comment by marcelpaulo** [comment]
Got some warnings from `dep` when running `make install`:

```
paulo@monk:~/go/src/github.com/knqyf263$ git clone https://github.com/knqyf263/pet.git
Cloning into 'pet'...
remote: Counting objects: 343, done.
remote: Total 343 (delta 0), reused 0 (delta 0), pack-reused 343
Receiving objects: 100% (343/343), 3.69 MiB | 3.54 MiB/s, done.
Resolving deltas: 100% (183/183), done.
paulo@monk:~/go/src/github.com/knqyf263$ cd pet/
paulo@monk:~/go/src/github.com/knqyf263/pet$ make install 
go get -u github.com/golang/dep/...
dep ensure
dep: WARNING: branch, version, revision, or source should be provided for "github.com/BurntSushi/toml"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/chzyer/readline"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/google/go-github"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/jroimartin/gocui"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/spf13/cobra"
dep: WARNING: branch, version, revision, or source should be provided for "golang.org/x/crypto"
dep: WARNING: branch, version, revision, or source should be provided for "golang.org/x/oauth2"
dep: WARNING: branch, version, revision, or source should be provided for "github.com/briandowns/spinner"
go install
```

Is there something that needs to be done about them ?

**Comment by knqyf263** [comment]
@marcelpaulo Thank you for the report!
This warning seems to come out if it is a new `dep` version.
I fixed config file.

**Comment by marcelpaulo** [comment]
Hey, @knqyf263, thanks for the speed-lightning fix !
