### ISSUE TITLE
Can't complete sync configuration because option -u to pet sync doesn't exist anymore

### ISSUE THREAD

**Issue by marcelpaulo** [knqyf263/pet#66]
Managed to build pet from source, and now I'm trying to configure syncing, following the instructions [here](https://github.com/knqyf263/pet#configuration). Got stuck here:

```
paulo@monk:~/go/src/github.com/knqyf263/pet$ pet sync -u
unknown shorthand flag: 'u' in -u
Usage of sync:
      --config string   config file (default is $HOME/.config/pet/config.toml)
      --debug           debug mode
  -h, --help            help for sync
unknown shorthand flag: 'u' in -u
```

The only keys I've changed in _$HOME/.config/pet/config.toml_ are `selectcmd`, which I set to **peco**, and `access_token` which I got from https://github.com/settings/tokens/new

**Comment by knqyf263** [comment]
@marcelpaulo Sorry... README was old.
I fixed documents. Please see https://github.com/knqyf263/pet#sync
https://github.com/knqyf263/pet/pull/70

In addition, please clone and rebuild because I fixed code.

**Comment by marcelpaulo** [comment]
Working like a chamr, @knqyf263 ! Thank you so much for your ever so swift replies and fixes !

I've built/installed/updated like this:

`go get -u github.com/knqyf263/pet`

**Comment by knqyf263** [comment]
Oh, not at all.

> go get -u github.com/knqyf263/pet
It's also OK!

**Comment by marcelpaulo** [comment]
I must mention: I was about to give up installing/using pet when I stumbled across the first problems owing to my lack of knowledge of Go, I even uninstalled it, but then you replied ever so swiftly and was always so willing to help, that I installed it again, and decided to work through the problems. I'm glad I did it !

Thanks, @knqyf263 !
