### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by varung** [knqyf263/pet#7]
go get github.com/knqyf263/pet

go/src/github.com/knqyf263/pet/cmd/sync.go:73: too many arguments in call to client.Gists.Create
go/src/github.com/knqyf263/pet/cmd/sync.go:77: retGist.GetID undefined (type *github.Gist has no field or method GetID)
go/src/github.com/knqyf263/pet/cmd/sync.go:79: too many arguments in call to client.Gists.Edit
go/src/github.com/knqyf263/pet/cmd/sync.go:94: too many arguments in call to client.Gists.Get

**Comment by knqyf263** [comment]
Is your [go-github](https://github.com/google/go-github) latest?
Please try the following command.

```
$ cd $GOPATH/src/github.com/google/go-github
$ git pull origin master
```

**Comment by varung** [comment]
Thanks, that fixed it. Sorry for false alarm!

**Comment by knqyf263** [comment]
No problem.
I should fix the version of library which `pet` uses.
Thanks!
