### ISSUE TITLE
best way to multilined  command ? 

### ISSUE THREAD

**Issue by keyolk** [knqyf263/pet#74]
Is there a example to use multiple lined  command in pet ?
seems below style is not works as expected  
```
command = """
echo a
echo b
echo c
"""

**Comment by DrakeW** [comment]
hi @keyolk , I created a workflow manager tool named [corgi](https://github.com/DrakeW/corgi) that supports multiple lined command, and you could also organize your command into separate steps in a workflow, feel free to try it out

**Comment by knqyf263** [comment]
I'm sorry for my too late reply. @vimsucks supported multiline command. 
https://github.com/knqyf263/pet/pull/103

Please try v0.3.5!!
