### ISSUE TITLE
support gitlab snippets

### ISSUE THREAD

**Issue by kaiwu** [knqyf263/pet#75]
pet is a nice tool, thanks !
under the [circumstances](https://blog.github.com/2018-06-04-github-microsoft/), any plan to support gitlab [snippets](https://docs.gitlab.com/ee/api/snippets.html) as `pet sync` remote target?

**Comment by knqyf263** [comment]
That sounds good.
I'd like to support gitlab snippets.
However, I usually don't use GitLab, so I welcome someone implement this!

**Comment by knqyf263** [comment]
@kaiwu I supported GitLab Snippets! I want you to use this!

**Comment by kaiwu** [comment]
@knqyf263 yes you are the man ! 
already used it on mac the moment it's in release folder, looking forward the rpm 🥇

**Comment by knqyf263** [comment]
@kaiwu I released v0.3.2 with rpm/deb package. Please try it!
https://github.com/knqyf263/pet/releases/tag/v0.3.2

**Comment by kaiwu** [comment]
@knqyf263  already did
 i am happy opt to leave the platform from which i acquired `pet`

**Comment by vglen** [comment]
Anyone else having issues getting pet to sync with gitlab? It only seems to want to use github, even if I use the --config option pointing to my config.tml with gitlab configured and no github block.

**Comment by MartinLoeper** [comment]
Just looked into the code: https://github.com/knqyf263/pet/blob/5d0345a656f82e6edcb60de5380f5f1d7274683b/sync/sync.go#L60

You must set the following to make this work:
```
[General]
    backend = "gitlab"
```

**Comment by papanito** [comment]
What url do I have to provide? I use the repo url but that seems not to work

```
Failed to upload snippet: Failed to create GitLab Snippet: Failed to create GitLab Snippet: POST https://gitlab.com/papanito/devenv/api/v4/snippets: 422 failed to parse unknown error format
```
