### ISSUE TITLE
sh: peco: command not found

### ISSUE THREAD

**Issue by upccup** [knqyf263/pet#8]
in CentOS7 and go version 1.8 

install pet with **go get github.com/knqyf263/pet** 

when i use pet edit and  pet list it work good, but when use pet exec  it report error: **sh: peco: command not found**

thx for eht aswsome tool

**Comment by xinsnake** [comment]
Hi @upccup , "peco" is a golang application that you would need to install yourself you are on CentOS7. I just tried it myself and here's briefly what you need to do:

1. Install glide (golang package manager, https://github.com/Masterminds/glide), which will give you the ability to download dependencies for peco.
1. Install peco (https://github.com/peco/peco), and you may want to follow the "Build Peco yourself" section (https://github.com/peco/peco#building-peco-yourself).
1. After you have it built using go build, then you can move that to your $GOHOME/bin, which will then allow you to use "pet exec"

Hopefully this helps. Thanks!

**Comment by knqyf263** [comment]
@xinsnake Thanks for your answer!

@upccup As xinsnake said, you can build `peco` yourself.
Otherwise, you can also just grab [the binary releases](https://github.com/peco/peco/releases) and drop it in your $PATH.

**Comment by upccup** [comment]
@xinsnake @knqyf263  thx  very much
