### ISSUE TITLE
Print the command itself before `pet exec`?

### ISSUE THREAD

**Issue by xingheng** [knqyf263/pet#80]
RT. Are there some ways to do this?

I use `pet` to save some long commands with placeholder replacement, once it executed via `pet exec`, I couldn't reveal what the final command text, it's so appreciated that `pet` could echo the command with the plain text before executing.

Will it support for this? Thanks!

**Comment by knqyf263** [comment]
@xingheng Thank you for the issue!
I implemented this feature.
Please try it!
