### ISSUE TITLE
Separate metadata field for language/syntax

### ISSUE THREAD

**Issue by daniels** [knqyf263/pet#85]
One thing that would be nice for publishing snippets (see #84) is if there was a standard way of indicating which syntax is used, so as to mark the snippet up for syntax highlighting. It can already be achieved by tags, but that would require some sort of convention for which tag is representing syntax as opposed to e.g. the tool used or any other tag.

I don’t know if you can make sense of what I wrote, but for example for an `awk` one liner, I would want to mark it for “sh” syntax highlighting but maybe also tag it “awk”.

If this is out of scope for the project it is easily achieved with some sort of tag prefix/suffix, though any third party scripts relying on this would need to be customized to match each users convention. I guess that doesn’t matter if I’m the only one who would like to publish/share my snippets this way ...

**Comment by RamiAwar** [comment]
Going to close this in favor for #84, I think that will include this.
