### ISSUE TITLE
sort criteria for `pet exec` respectively `pet search`

### ISSUE THREAD

**Issue by riscie** [knqyf263/pet#87]
Hi there

First of all, I want to provide my deep respect for this project. I think it's a fantastic tool. Very well done :+1: :+1: 
What I wanted to ask is, if there is an easy way to order (sort) the fzf (peco) output of `pet exec`respectively `pet search`. I could not find an such option on my look trough the docs and a brief look at the code.
For me personally it would be most intuitive to sort the output alphabetically. (ymmv :smile:)

If something like this does not exist I can also offer to create a pr.

Kindly, matthias

**Comment by knqyf263** [comment]
@riscie Thank you for creating an issue!
Currently `pet` doesn't have `sort` option.
As a workaround, you can use pipe in selectcmd like this.
`selectcmd = "sort | fzf"`

However, this workaround is inflexible.
If you can create a PR, I'm soooooo happy!!

**Comment by riscie** [comment]
Hi @knqyf263 
Thanks for replying back so far. So I've created a PR (#88).
I hope this implementation works for you. Sorry my go is quite rusty (no pun intended).

**Comment by knqyf263** [comment]
I've merged. Thank you so much!

**Comment by riscie** [comment]
Nice! I am more than happy to help!
