### ISSUE TITLE
Error:  sh: 1: vim: not found

### ISSUE THREAD

**Issue by sbrl** [knqyf263/pet#91]
Sorry for the double-issue, but I've found a bug!

On my system, I don't have `vim` installed. To this end, doing `pet configure` causes an error to be thrown.

I suggest the following behaviour:

 - If the `sensible-editor` command is installed, use that
 - If the `EDITOR` environment variable is present, take the editor's binary name from there (e.g. an example value might be `EDITOR=nano`)

**Comment by knqyf263** [comment]
@sbrl Thank you for reporting an issue.
I supported `sensible_command`.
Please try it.

**Comment by sbrl** [comment]
Awesome, thanks @knqyf263! I don't have a go compiler installed, but I'll certainly try it out as soon as the next release is out :-)

**Comment by knqyf263** [comment]
@sbrl I releaesd v0.3.4!
