### ISSUE TITLE
Interactive shell reads fail when using placeholders

### ISSUE THREAD

**Issue by MohamedKari** [knqyf263/pet#97]
Executing `openssl aes-256-cbc -a -salt -in test.csv -out test.csv.enc` requires typing the password twice. 

Entering the command by hand in the terminal and then typing the password twice works.

Saving the command exactly this way to pet and then typing the password twice works.

Saving the command with a `<placeholder>` for the filename and executing it, will create the same command. But typing the password the first time will fail when hitting enter and the password will be printed in the next $ shell line. 

Seems that when using placeholders, the characters are not reaching the std input of openssl. Executing the command manually again, will also fail from then on with the same error.

Version 3.2.0 on macOS Sierra 10.12.

![image](https://user-images.githubusercontent.com/29415552/53681683-3411ac80-3ced-11e9-8eba-36d74c15adf8.png)

**Comment by knqyf263** [comment]
Thank you for the issue! It is also reproduced in my environment. However, other interactive commands such as `psql -U <user> -h localhost` go well. So, it may be an openssl problem. Do you know any other commands that reproduce this problem? 

If not, it is possible to work around with this command `openssl aes-256-cbc -a -salt -in <input_file> -out <input_file>.enc -pass pass:<password>`.

**Comment by RamiAwar** [comment]
Tested your command manually today and it seems to be working. Guess openssl updates fixed this somehow! 🤷🏼 

Going to close, re-open if it reoccurs!
