### ISSUE TITLE
pet-snippet.toml is empty

### ISSUE THREAD

**Issue by gggitpl** [knqyf263/pet#99]
New install pet, and sync gist prompts are as follows

pet-snippet.toml is empty

v0.3.4

There is also a case of overwriting the gist record, resulting in a missing code snippet

**Comment by pbek** [comment]
I guess #110 would fix the issue.

**Comment by knqyf263** [comment]
As pbek may have fixed this issue, I closed this issue. If you reproduce this problem, please reopen this.
